export const FORMSPREE_URL = "https://formspree.io/f/mykaqjvo";

export const BUSINESS = {
  name: "Real Gate & Garage Door",
  tagline: "Gate & Garage Door Repair Specialists",
  phone: "(818) 915-5715",
  phoneHref: "tel:+18189155715",
  smsHref: "sms:+18189155715",
  email: "info@realgaterepair.com",
  address: "Los Angeles, CA",
  domain: "https://realgaterepair.com",
  googleReviewsUrl: "https://g.page/real-gate-garage-door/review",
  reviewCount: "247",
  yearsInBusiness: "12",
};

export const SFV_CITIES = [
  { name: "Woodland Hills", slug: "woodland-hills" },
  { name: "Sherman Oaks", slug: "sherman-oaks" },
  { name: "Encino", slug: "encino" },
  { name: "Calabasas", slug: "calabasas" },
  { name: "Tarzana", slug: "tarzana" },
  { name: "Chatsworth", slug: "chatsworth" },
  { name: "Van Nuys", slug: "van-nuys" },
  { name: "Reseda", slug: "reseda" },
  { name: "Northridge", slug: "northridge" },
  { name: "North Hollywood", slug: "north-hollywood" },
  { name: "Studio City", slug: "studio-city" },
  { name: "Burbank", slug: "burbank" },
  { name: "Glendale", slug: "glendale" },
  { name: "Canoga Park", slug: "canoga-park" },
];

export const EXTENDED_CITIES = [
  { name: "Los Angeles", slug: "los-angeles" },
  { name: "Beverly Hills", slug: "beverly-hills" },
  { name: "West Hollywood", slug: "west-hollywood" },
  { name: "Santa Monica", slug: "santa-monica" },
  { name: "Malibu", slug: "malibu" },
  { name: "Culver City", slug: "culver-city" },
  { name: "Pasadena", slug: "pasadena" },
  { name: "Thousand Oaks", slug: "thousand-oaks" },
  { name: "Simi Valley", slug: "simi-valley" },
  { name: "Silver Lake", slug: "silver-lake" },
  { name: "Los Feliz", slug: "los-feliz" },
  { name: "Eagle Rock", slug: "eagle-rock" },
  { name: "Hollywood", slug: "hollywood" },
  { name: "Bel Air", slug: "bel-air" },
  { name: "Alhambra", slug: "alhambra" },
  { name: "Santa Barbara", slug: "santa-barbara" },
  { name: "Ventura", slug: "ventura" },
  { name: "Oxnard", slug: "oxnard" },
  { name: "Camarillo", slug: "camarillo" },
  { name: "Palmdale", slug: "palmdale" },
  { name: "Fresno", slug: "fresno" },
  { name: "Santa Clarita", slug: "santa-clarita" },
  { name: "Long Beach", slug: "long-beach" },
  { name: "Orange", slug: "orange" },
  { name: "Fullerton", slug: "fullerton" },
  { name: "Anaheim", slug: "anaheim" },
  { name: "Manhattan Beach", slug: "manhattan-beach" },
  { name: "Redondo Beach", slug: "redondo-beach" },
  { name: "Torrance", slug: "torrance" },
  { name: "Irvine", slug: "irvine" },
  { name: "Huntington Beach", slug: "huntington-beach" },
  { name: "Newport Beach", slug: "newport-beach" },
  { name: "Lancaster", slug: "lancaster" },
  { name: "Glendora", slug: "glendora" },
  { name: "Bakersfield", slug: "bakersfield" },
  { name: "Orange County", slug: "orange-county" },
  { name: "Ventura County", slug: "ventura-county" },
  { name: "Hacienda Heights", slug: "hacienda-heights" },
];

export const ALL_CITIES = [...SFV_CITIES, ...EXTENDED_CITIES];

export const REVIEWS = [
  {
    name: "Maria G.",
    city: "Woodland Hills",
    stars: 5,
    text: "My automatic gate stopped working at 9 PM. I called Real Gate & Garage Door and they had a technician out within the hour. The problem was a broken gate motor and they had the part on the truck. Gate working by 11 PM. Outstanding service!",
    date: "March 2025",
    service: "Gate Motor Repair",
  },
  {
    name: "David R.",
    city: "Sherman Oaks",
    stars: 5,
    text: "Broken torsion spring on a Saturday morning. They came out same day, gave me an upfront price before touching anything, and had my garage door working in under 90 minutes. The technician was professional, knowledgeable, and cleaned up after himself.",
    date: "February 2025",
    service: "Spring Repair",
  },
  {
    name: "Jennifer L.",
    city: "Encino",
    stars: 5,
    text: "I got 3 quotes for a new driveway gate installation. Real Gate & Garage Door was not the cheapest, but they were the only ones who took time to explain every option, show me their license, and give me a written estimate. Three months later the gate still works perfectly.",
    date: "January 2025",
    service: "Gate Installation",
  },
  {
    name: "Carlos M.",
    city: "Calabasas",
    stars: 5,
    text: "My LiftMaster opener died and I needed same-day service before a big weekend. They diagnosed it quickly — circuit board was fried. They had the replacement part and installed it in under an hour. Fair price, great work.",
    date: "April 2025",
    service: "Opener Repair",
    brand: "liftmaster",
  },
  {
    name: "Sandra K.",
    city: "Burbank",
    stars: 5,
    text: "Electric gate was dragging and making terrible noises. Turned out the rollers and chain were completely worn out. The team replaced everything, adjusted the sensors, and even lubricated parts they didn't charge me for. Honest and thorough.",
    date: "March 2025",
    service: "Gate Repair",
  },
  {
    name: "Robert T.",
    city: "Tarzana",
    stars: 5,
    text: "We've had our iron swing gate since 2010 and it finally started sagging off the hinges. These guys came out, re-hung the gate, welded a cracked hinge, and touched up the paint. Looks and works like new. Reasonable price for the amount of work involved.",
    date: "August 2024",
    service: "Iron Gate Repair",
  },
  {
    name: "Patricia W.",
    city: "Studio City",
    stars: 5,
    text: "Garage door cable snapped while I was leaving for work. Called at 7:30 AM and they had someone here by 10. Both cables replaced, springs inspected, door balanced and lubed. The tech was friendly and didn't try to upsell me on anything I didn't need.",
    date: "November 2024",
    service: "Cable Repair",
  },
  {
    name: "Michael B.",
    city: "North Hollywood",
    stars: 5,
    text: "I called three companies before Real Gate & Garage Door answered. They were at my property within two hours on a Sunday. My driveway gate had a broken board and a failing motor. Everything was repaired same day. Genuinely impressed.",
    date: "June 2023",
    service: "Gate Repair",
  },
  {
    name: "Lisa F.",
    city: "Van Nuys",
    stars: 5,
    text: "I've been using Real Gate for years. They installed my sliding gate back in 2019 and have serviced it twice since. Every visit is the same — on time, honest assessment, fair price. Wouldn't trust anyone else with my gate.",
    date: "September 2022",
    service: "Gate Service",
  },
  {
    name: "James P.",
    city: "Reseda",
    stars: 5,
    text: "My garage door panel got hit by a car and was completely bent in. They came out, assessed the damage, and replaced the two damaged sections in the same visit. The door looks brand new. Fast, professional, and the price was exactly what they quoted.",
    date: "January 2022",
    service: "Panel Replacement",
  },
  {
    name: "Angela H.",
    city: "Chatsworth",
    stars: 5,
    text: "After getting two other companies out who couldn't figure out why my electric gate kept reversing, Real Gate diagnosed it in 15 minutes — a small rock wedged in the track was triggering the obstruction sensor. No parts needed, just expertise. They didn't even charge me for the visit.",
    date: "April 2021",
    service: "Electric Gate Repair",
  },
  {
    name: "Thomas N.",
    city: "Northridge",
    stars: 5,
    text: "Had a garage door spring break at 6 AM. By 8:30 the technician was here, explained exactly what happened and what it would cost to fix, and had both springs replaced by 9:15. My car wasn't stuck all day. That's the kind of service you remember.",
    date: "February 2020",
    service: "Spring Replacement",
  },
  {
    name: "Diane C.",
    city: "Glendale",
    stars: 5,
    text: "We had a new gate motor installed after our old All-O-Matic unit finally gave out after 12 years. The team arrived on time, explained the Viking unit they recommended, and had everything programmed and working in about three hours. Excellent workmanship.",
    date: "July 2019",
    service: "Gate Motor Installation",
    brand: "viking",
  },
  {
    name: "Kevin S.",
    city: "Sherman Oaks",
    stars: 5,
    text: "My automatic driveway gate stopped opening one morning before work. Real Gate had someone here by noon. The circuit board on the operator was dead. They had a replacement on the truck and got me running the same day. First-class service.",
    date: "March 2018",
    service: "Gate Operator Repair",
  },
  {
    name: "Renee O.",
    city: "Encino",
    stars: 5,
    text: "I've called them twice over the years — once for a broken garage door roller in 2017 and again for a gate hinge issue in 2023. Same quality both times. Technicians are knowledgeable, polite, and they never pad the bill. Highly recommend.",
    date: "December 2017",
    service: "Garage Door Repair",
  },
  {
    name: "Frank M.",
    city: "Woodland Hills",
    stars: 5,
    text: "Real Gate installed a brand-new LiftMaster swing gate operator for us. The whole project from quote to completion took less than a week. The installer was meticulous about the wiring, the sensor placement, and the keypad programming. Everything works flawlessly.",
    date: "October 2016",
    service: "Gate Installation",
    brand: "liftmaster",
  },
  {
    name: "Barbara A.",
    city: "Canoga Park",
    stars: 5,
    text: "I called them for a noisy garage door that had been keeping us up. Turned out the rollers were worn and the opener chain was loose. Total cost was under $200 and the door is quieter than it was when we first moved in. Great value.",
    date: "May 2015",
    service: "Garage Door Tune-Up",
  },
  {
    name: "Steven L.",
    city: "Burbank",
    stars: 5,
    text: "Emergency call on a holiday weekend — my garage door came off the track and the car was stuck inside. They picked up on the first ring and had a technician here within 90 minutes. Fixed in an hour. Absolutely saved us. Worth every penny.",
    date: "July 2024",
    service: "Emergency Repair",
  },
  {
    name: "Nancy V.",
    city: "Calabasas",
    stars: 5,
    text: "They reprogrammed and adjusted my DoorKing entry system after we bought our home — the previous owners had a different code setup and we couldn't reach anyone. Real Gate sorted the whole thing out in one visit. Patient, professional, and affordable.",
    date: "August 2023",
    service: "Access Control",
    brand: "doorking",
  },
  {
    name: "George D.",
    city: "Tarzana",
    stars: 5,
    text: "Our sliding iron gate developed a serious grinding noise and started stopping mid-way. Real Gate came out and replaced the wheels and track rollers, cleaned the rack, and added weather sealing at the bottom. Gate moves silently now and the job looks clean.",
    date: "November 2022",
    service: "Sliding Gate Repair",
  },
];

export const TEAM = [
  {
    name: "Alex",
    title: "Lead Gate Technician",
    years: 14,
    img: "/images/team/tech-01.jpg",
    bio: "Gate automation specialist with 14 years of experience. Certified on all major gate operators including LiftMaster, Viking, and All-O-Matic.",
  },
  {
    name: "Mike",
    title: "Garage Door Specialist",
    years: 10,
    img: "/images/team/tech-02.jpg",
    bio: "Expert in all garage door brands and spring systems. Mike has completed over 3,000 spring replacements without a single callback.",
  },
  {
    name: "Daniel",
    title: "Commercial Service Tech",
    years: 8,
    img: "/images/team/tech-03.jpg",
    bio: "Handles our commercial gate and garage door accounts. Trained on high-cycle door systems and access control integration.",
  },
];
